language: 
  - cpp

before_install:
  - pip install --user cpp-coveralls

script:
  - cmake -H. -Bbuild
  - cd build
  - cmake --build .
  - ctest
  - cd ..

after_success:
  - coveralls --exclude build/CMakeFiles/ --exclude build/googletest-src/ --gcov-options '\-lp'
