language: 
  - cpp

before_install:
  - pip install --user cpp-coveralls

before_script:
  - mkdir build
  - cd build
  - cmake -DENABLE_COVERAGE=ON ..

script:
  - cmake -H. -Bbuild
  - cd build
  - cmake --build .
  - ctest
    
after_success:
  - coveralls --root .. --exclude build/CMakeFiles/ --exclude build/googletest-src/
