language: 
  - cpp

before_install:
  - pip install --user cpp-coveralls

script:
  - cmake -H. -Bbuild
  - cd build
  - cmake --build .
  - ctest

after_success:
  - coveralls --root .. --exclude build/CMakeFiles/ --exclude build/googletest-src/
