language: 
  - cpp
 
compiler:
  - clang

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test

before_install:
  - pip install --user cpp-coveralls
  - sudo apt-get update -qq
  - sudo apt-get install libboost-dev
  
before_script:
  - mkdir build
  - cd build
  - cmake -DENABLE_COVERAGE=ON ..
  - cd ..
  
script:
  - cd build
  - cmake --build .
  - ctest .
    
after_success:
  - coveralls --exclude build/CMakeFiles/ --exclude build/gtest/ --exclude build/args/ --gcov "llvm-cov gcov" --gcov-options '\-lp'
