
language: cpp

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-6
      - g++-6

before_install:
  - pip install --user cpp-coveralls

before_script:
  - mkdir build
  - cd build
  - cmake -DENABLE_COVERAGE=ON -DCMAKE_CXX_COMPILER="g++-6" ..
  - mkdir output

script:
  - cmake --build .
  - ctest .
  - cd ..

env:
  global:
    - GH_REPO_NAME=leistungsnachweis-algo
    - DOXYFILE=$TRAVIS_BUILD_DIR/Doxyfile
    - GH_REPO_REF=github.com/ob-algdatii-ss18/leistungsnachweis-algo.git
    
after_success:
- coveralls --root . --exclude googletest --exclude test --exclude "build/CMakeFiles/feature_tests.*"
