language: 
  - cpp

addons:
  apt:
    packages:
      - doxygen

before_install:
  - pip install --user cpp-coveralls

script:
  - cmake -H. -Bbuild
  - cd build
  - cmake --build .
  - ctest
  - cd ..
  - cd docs
  - doxygen
  - make html

after_success:
  - coveralls --root .. --exclude build/CMakeFiles/ --exclude build/googletest-src/ --gcov-options '\-lp'
